displayName: Demo Plugin
type: middleware

import: github.com/bladedancer/traefik-policy/policyplugin

summary: '[Demo] Add Request Header'

testData:
  Headers:
    X-Demo: test
    X-URL: '{{URL}}'
