apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  ports:
    - name: http-traffic
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-traffic
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http-proxy
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
