// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy.proto

package policyservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{0}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type InvokeRequest struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Policy               string            `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	EndOfStream          bool              `protobuf:"varint,5,opt,name=endOfStream,proto3" json:"endOfStream,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeRequest) Reset()         { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()    {}
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{1}
}

func (m *InvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeRequest.Unmarshal(m, b)
}
func (m *InvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeRequest.Marshal(b, m, deterministic)
}
func (m *InvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeRequest.Merge(m, src)
}
func (m *InvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeRequest.Size(m)
}
func (m *InvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeRequest proto.InternalMessageInfo

func (m *InvokeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InvokeRequest) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *InvokeRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *InvokeRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *InvokeRequest) GetEndOfStream() bool {
	if m != nil {
		return m.EndOfStream
	}
	return false
}

type InvokeReply struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	EndOfStream          bool              `protobuf:"varint,4,opt,name=endOfStream,proto3" json:"endOfStream,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeReply) Reset()         { *m = InvokeReply{} }
func (m *InvokeReply) String() string { return proto.CompactTextString(m) }
func (*InvokeReply) ProtoMessage()    {}
func (*InvokeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{2}
}

func (m *InvokeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeReply.Unmarshal(m, b)
}
func (m *InvokeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeReply.Marshal(b, m, deterministic)
}
func (m *InvokeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeReply.Merge(m, src)
}
func (m *InvokeReply) XXX_Size() int {
	return xxx_messageInfo_InvokeReply.Size(m)
}
func (m *InvokeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeReply.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeReply proto.InternalMessageInfo

func (m *InvokeReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InvokeReply) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *InvokeReply) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *InvokeReply) GetEndOfStream() bool {
	if m != nil {
		return m.EndOfStream
	}
	return false
}

// Policy Server configuration
type Config struct {
	// The cluster name of the policy service.
	Clustername string `protobuf:"bytes,1,opt,name=clustername,proto3" json:"clustername,omitempty"`
	// The policy execution timeout.
	Timeout              uint32   `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{3}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetClustername() string {
	if m != nil {
		return m.Clustername
	}
	return ""
}

func (m *Config) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func init() {
	proto.RegisterType((*Chunk)(nil), "policyservice.Chunk")
	proto.RegisterType((*InvokeRequest)(nil), "policyservice.InvokeRequest")
	proto.RegisterMapType((map[string]string)(nil), "policyservice.InvokeRequest.HeadersEntry")
	proto.RegisterType((*InvokeReply)(nil), "policyservice.InvokeReply")
	proto.RegisterMapType((map[string]string)(nil), "policyservice.InvokeReply.HeadersEntry")
	proto.RegisterType((*Config)(nil), "policyservice.Config")
}

func init() { proto.RegisterFile("policy.proto", fileDescriptor_ac3b897852294d6a) }

var fileDescriptor_ac3b897852294d6a = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x4e, 0xab, 0x40,
	0x14, 0xc6, 0x33, 0xd0, 0x3f, 0xf7, 0x9e, 0xd2, 0x9b, 0x9b, 0xc9, 0xcd, 0x0d, 0x69, 0x5c, 0xd0,
	0x6e, 0x44, 0x17, 0xc4, 0xd4, 0x8d, 0xe9, 0x4e, 0xd1, 0x44, 0x13, 0x13, 0x1b, 0xba, 0x75, 0x43,
	0xe1, 0xb4, 0x25, 0x85, 0x19, 0x1c, 0x06, 0x94, 0xd7, 0xf1, 0x91, 0x7c, 0x10, 0x9f, 0xc1, 0x74,
	0x80, 0xd8, 0x6a, 0xaa, 0x1b, 0x77, 0xf3, 0x7d, 0x39, 0xf3, 0xcd, 0xf7, 0x83, 0x03, 0x46, 0xca,
	0xe3, 0x28, 0x28, 0x9d, 0x54, 0x70, 0xc9, 0x69, 0xbf, 0x52, 0x19, 0x8a, 0x22, 0x0a, 0x70, 0x34,
	0x84, 0xb6, 0xbb, 0xca, 0xd9, 0x9a, 0x9a, 0xd0, 0x75, 0x39, 0x93, 0xc8, 0xa4, 0x49, 0x2c, 0x62,
	0x1b, 0x5e, 0x23, 0x47, 0xaf, 0x04, 0xfa, 0x37, 0xac, 0xe0, 0x6b, 0xf4, 0xf0, 0x21, 0xc7, 0x4c,
	0xd2, 0x3f, 0xa0, 0x45, 0xa1, 0x1a, 0xfb, 0xed, 0x69, 0x51, 0x48, 0xff, 0x43, 0xa7, 0x4a, 0x35,
	0x35, 0xe5, 0xd5, 0x8a, 0xba, 0xd0, 0x5d, 0xa1, 0x1f, 0xa2, 0xc8, 0x4c, 0xdd, 0xd2, 0xed, 0xde,
	0xf8, 0xc8, 0xd9, 0x79, 0xdd, 0xd9, 0x89, 0x75, 0xae, 0xab, 0xd9, 0x2b, 0x26, 0x45, 0xe9, 0x35,
	0x37, 0x29, 0x85, 0xd6, 0x9c, 0x87, 0xa5, 0xd9, 0x52, 0xad, 0xd4, 0x99, 0x5a, 0xd0, 0x43, 0x16,
	0xde, 0x2d, 0x66, 0x52, 0xa0, 0x9f, 0x98, 0x6d, 0x8b, 0xd8, 0xbf, 0xbc, 0x6d, 0x6b, 0x30, 0x01,
	0x63, 0x3b, 0x8e, 0xfe, 0x05, 0x7d, 0x8d, 0x65, 0xdd, 0x79, 0x73, 0xa4, 0xff, 0xa0, 0x5d, 0xf8,
	0x71, 0x8e, 0x75, 0xe7, 0x4a, 0x4c, 0xb4, 0x33, 0x32, 0x7a, 0x21, 0xd0, 0x6b, 0x9a, 0xa5, 0x71,
	0xf9, 0x09, 0xf7, 0xfc, 0x1d, 0x4b, 0x53, 0x58, 0x87, 0x7b, 0xb0, 0xd2, 0xb8, 0xfc, 0x06, 0x4a,
	0xdf, 0x0f, 0xd5, 0xfa, 0x59, 0xa8, 0x4b, 0xe8, 0xb8, 0x9c, 0x2d, 0xa2, 0xe5, 0xe6, 0x9d, 0x20,
	0xce, 0x33, 0x89, 0x82, 0xf9, 0x09, 0xd6, 0xb7, 0xb7, 0xad, 0xcd, 0x2e, 0xc8, 0x28, 0x41, 0x9e,
	0x4b, 0x95, 0xd3, 0xf7, 0x1a, 0x39, 0xbe, 0x07, 0x63, 0xaa, 0x50, 0x67, 0x28, 0x0a, 0x14, 0xf4,
	0x16, 0x8c, 0x0a, 0xb6, 0x72, 0xe9, 0xc1, 0x57, 0x3f, 0x78, 0x30, 0xd8, 0xff, 0x9d, 0x6c, 0x72,
	0x42, 0x2e, 0x8e, 0x61, 0x18, 0xf0, 0xc4, 0xf1, 0x9f, 0x1e, 0xfd, 0xf2, 0xc3, 0xe8, 0x12, 0x19,
	0x0a, 0x5f, 0x62, 0x38, 0x25, 0xcf, 0x9a, 0x36, 0x9d, 0xcd, 0x3b, 0x6a, 0x9d, 0x4f, 0xdf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x42, 0xdb, 0x94, 0x08, 0xde, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PolicyServerClient is the client API for PolicyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolicyServerClient interface {
	InvokePolicy(ctx context.Context, opts ...grpc.CallOption) (PolicyServer_InvokePolicyClient, error)
}

type policyServerClient struct {
	cc *grpc.ClientConn
}

func NewPolicyServerClient(cc *grpc.ClientConn) PolicyServerClient {
	return &policyServerClient{cc}
}

func (c *policyServerClient) InvokePolicy(ctx context.Context, opts ...grpc.CallOption) (PolicyServer_InvokePolicyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PolicyServer_serviceDesc.Streams[0], "/policyservice.PolicyServer/InvokePolicy", opts...)
	if err != nil {
		return nil, err
	}
	x := &policyServerInvokePolicyClient{stream}
	return x, nil
}

type PolicyServer_InvokePolicyClient interface {
	Send(*InvokeRequest) error
	Recv() (*InvokeReply, error)
	grpc.ClientStream
}

type policyServerInvokePolicyClient struct {
	grpc.ClientStream
}

func (x *policyServerInvokePolicyClient) Send(m *InvokeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *policyServerInvokePolicyClient) Recv() (*InvokeReply, error) {
	m := new(InvokeReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PolicyServerServer is the server API for PolicyServer service.
type PolicyServerServer interface {
	InvokePolicy(PolicyServer_InvokePolicyServer) error
}

// UnimplementedPolicyServerServer can be embedded to have forward compatible implementations.
type UnimplementedPolicyServerServer struct {
}

func (*UnimplementedPolicyServerServer) InvokePolicy(srv PolicyServer_InvokePolicyServer) error {
	return status.Errorf(codes.Unimplemented, "method InvokePolicy not implemented")
}

func RegisterPolicyServerServer(s *grpc.Server, srv PolicyServerServer) {
	s.RegisterService(&_PolicyServer_serviceDesc, srv)
}

func _PolicyServer_InvokePolicy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolicyServerServer).InvokePolicy(&policyServerInvokePolicyServer{stream})
}

type PolicyServer_InvokePolicyServer interface {
	Send(*InvokeReply) error
	Recv() (*InvokeRequest, error)
	grpc.ServerStream
}

type policyServerInvokePolicyServer struct {
	grpc.ServerStream
}

func (x *policyServerInvokePolicyServer) Send(m *InvokeReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *policyServerInvokePolicyServer) Recv() (*InvokeRequest, error) {
	m := new(InvokeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PolicyServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "policyservice.PolicyServer",
	HandlerType: (*PolicyServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokePolicy",
			Handler:       _PolicyServer_InvokePolicy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "policy.proto",
}
